<?php
/**
 * JUExcBotHits
 *
 * @package          Joomla.Site
 * @subpackage       plg_juexcbothits
 *
 * @author           Denys Nosov, denys@joomla-ua.org
 * @copyright        2016-2017 (C) Joomla! Ukraine, http://joomla-ua.org. All rights reserved.
 * @license          GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

/**
 * JUExcBotHits Plugin.
 *
 * @since  1.0
 */
class PlgSystemExBotHits extends JPlugin
{
    private static $agents = [
        "008",
        "ABACHOBot",
        "Accoona-AI-Agent",
        "AddSugarSpiderBot",
        "AnyApexBot",
        "Arachmo",
        "B-l-i-t-z-B-O-T",
        "BecomeBot",
        "BeslistBot",
        "BillyBobBot",
        "Bimbot",
        "Bingbot",
        "BlitzBOT",
        "boitho.com-dc",
        "boitho.com-robot",
        "btbot",
        "CatchBot",
        "Cerberian Drtrs",
        "Charlotte",
        "ConveraCrawler",
        "cosmos",
        "Covario IDS",
        "DataparkSearch",
        "DiamondBot",
        "Discobot",
        "Dotbot",
        "EARTHCOM.info",
        "EmeraldShield.com WebBot",
        "envolk[ITS]spider",
        "EsperanzaBot",
        "Exabot",
        "FAST Enterprise Crawler",
        "FAST-WebCrawler",
        "FDSE robot",
        "FindLinks",
        "FurlBot",
        "FyberSpider",
        "g2crawler",
        "Gaisbot",
        "GalaxyBot",
        "genieBot",
        "Gigabot",
        "Girafabot",
        "GurujiBot",
        "HappyFunBot",
        "hl_ftien_spider",
        "Holmes",
        "htdig",
        "iaskspider",
        "ia_archiver",
        "iCCrawler",
        "ichiro",
        "igdeSpyder",
        "IRLbot",
        "IssueCrawler",
        "Jaxified Bot",
        "Jyxobot",
        "KoepaBot",
        "L.webis",
        "LapozzBot",
        "Larbin",
        "LDSpider",
        "LexxeBot",
        "Linguee Bot",
        "LinkWalker",
        "lmspider",
        "lwp-trivial",
        "mabontland",
        "magpie-crawler",
        "Mediapartners-Google",
        "MJ12bot",
        "MLBot",
        "Mnogosearch",
        "mogimogi",
        "MojeekBot",
        "Moreoverbot",
        "Morning Paper",
        "msnbot",
        "MSRBot",
        "MVAClient",
        "mxbot",
        "NetResearchServer",
        "NetSeer Crawler",
        "NewsGator",
        "NG-Search",
        "nicebot",
        "noxtrumbot",
        "Nusearch Spider",
        "NutchCVS",
        "Nymesis",
        "obot",
        "oegp",
        "omgilibot",
        "OmniExplorer_Bot",
        "OOZBOT",
        "Orbiter",
        "PageBitesHyperBot",
        "Peew",
        "polybot",
        "Pompos",
        "PostPost",
        "Psbot",
        "PycURL",
        "Qseero",
        "Radian6",
        "RAMPyBot",
        "RufusBot",
        "SandCrawler",
        "SBIder",
        "ScoutJet",
        "Scrubby",
        "SearchSight",
        "Seekbot",
        "semanticdiscovery",
        "Sensis Web Crawler",
        "SEOChat::Bot",
        "SeznamBot",
        "Shim-Crawler",
        "ShopWiki",
        "Shoula robot",
        "silk",
        "Sitebot",
        "Snappy",
        "sogou spider",
        "Sosospider",
        "Speedy Spider",
        "Sqworm",
        "StackRambler",
        "suggybot",
        "SurveyBot",
        "SynooBot",
        "Teoma",
        "TerrawizBot",
        "TheSuBot",
        "Thumbnail.CZ robot",
        "TinEye",
        "truwoGPS",
        "TurnitinBot",
        "TweetedTimes Bot",
        "TwengaBot",
        "updated",
        "Urlfilebot",
        "Vagabondo",
        "VoilaBot",
        "Vortex",
        "voyager",
        "VYU2",
        "webcollage",
        "Websquash.com",
        "wf84",
        "WoFindeIch Robot",
        "WomlpeFactory",
        "Xaldon_WebSpider",
        "yacy",
        "Yahoo! Slurp",
        "Yahoo! Slurp China",
        "YahooSeeker",
        "YahooSeeker-Testing",
        "Yasaklibot",
        "Yeti",
        "YodaoBot",
        "yoogliFetchAgent",
        "YoudaoBot",
        "Zao",
        "Zealbot",
        "zspider",
        "ZyBorg",
        "2ip.ru",
        "a.pr-cy.ru",
        "ADmantX",
        "AdsBot",
        "curl/",
        "FeedBurner",
        "Feedly",
        "HTTP_Request2",
        "Huifikator",
        "libwww-perl",
        "Java/",
        "MetaURI API",
        "mfibot",
        "Mojolicious",
        "Screaming Frog SEO Spider",
        "Python-urllib",
        "PocketParser",
        "Scrapy",
        "Nodemeter",
        "NewRelicPinger",
        "ABCdatos BotLink",
        "Acme.Spider",
        "Ahoy! The Homepage Finder",
        "Alkaline",
        "Anthill",
        "Walhello appie",
        "Arachnophilia",
        "Arale",
        "Araneo",
        "AraybOt",
        "ArchitextSpider",
        "Aretha",
        "ARIADNE",
        "arks",
        "AskJeeves",
        "ASpider (Associative Spider)",
        "ATN Worldwide",
        "Atomz.com Search Robot",
        "AURESYS",
        "BackRub",
        "Bay Spider",
        "Big Brother",
        "Bjaaland",
        "BlackWidow",
        "Die Blinde Kuh",
        "Bloodhound",
        "Borg-Bot",
        "BoxSeaBot",
        "bright.net caching robot",
        "BSpider",
        "CACTVS Chemistry Spider",
        "Calif",
        "Cassandra",
        "Digimarc Marcspider/CGI",
        "Checkbot",
        "ChristCrawler.com",
        "churl",
        "cIeNcIaFiCcIoN.nEt",
        "CMC/0.01",
        "Collective",
        "Combine System",
        "Conceptbot",
        "ConfuzzledBot",
        "CoolBot",
        "Web Core / Roots",
        "XYLEME Robot",
        "Internet Cruiser Robot",
        "Cusco",
        "CyberSpyder Link Test",
        "CydralSpider",
        "Desert Realm Spider",
        "DeWeb(c) Katalog/Index",
        "DienstSpider",
        "Digger",
        "Digital Integrity Robot",
        "Direct Hit Grabber",
        "DNAbot",
        "DownLoad Express",
        "DragonBot",
        "DWCP (Dridus' Web Cataloging Project)",
        "e-collector",
        "EbiNess",
        "EIT Link Verifier Robot",
        "ELFINBOT",
        "Emacs-w3 Search Engine",
        "ananzi",
        "esculapio",
        "Esther",
        "Evliya Celebi",
        "FastCrawler",
        "Fluid Dynamics Search Engine robot",
        "Felix IDE",
        "Wild Ferret Web Hopper #1, #2, #3",
        "FetchRover",
        "fido",
        "Hamahakki",
        "KIT-Fireball",
        "Fish search",
        "Fouineur",
        "Robot Francoroute",
        "Freecrawl",
        "FunnelWeb",
        "gammaSpider, FocusedCrawler",
        "gazz",
        "GCreep",
        "GetBot",
        "GetURL",
        "Golem",
        "Grapnel/0.01 Experiment",
        "Griffon",
        "Gromit",
        "Northern Light Gulliver",
        "Gulper Bot",
        "HamBot",
        "Harvest",
        "havIndex",
        "HI (HTML Index) Search",
        "Hometown Spider Pro",
        "ht://Dig",
        "HTMLgobble",
        "Hyper-Decontextualizer",
        "iajaBot",
        "IBM_Planetwide",
        "Popular Iconoclast",
        "Ingrid",
        "Imagelock",
        "IncyWincy",
        "Informant",
        "InfoSeek Robot 1.0",
        "Infoseek Sidewinder",
        "Infoseek 1",
        "Infoseek 2",
        "InfoSpiders",
        "Inspector Web",
        "IntelliAgent",
        "I, Robot",
        "Iron33",
        "Israeli-search",
        "JavaBee",
        "JBot Java Web Robot",
        "JCrawler",
        "Jeeves",
        "JoBo Java Web Robot",
        "Jobot",
        "JoeBot",
        "The Jubii Indexing Robot",
        "JumpStation",
        "image.kapsi.net",
        "Katipo",
        "KDD-Explorer",
        "Kilroy",
        "KO_Yappo_Robot",
        "LabelGrabber",
        "legs",
        "Link Validator",
        "LinkScan",
        "Lockon",
        "logo.gif Crawler",
        "Lycos",
        "Mac WWWWorm",
        "Magpie",
        "marvin/infoseek",
        "Mattie",
        "MediaFox",
        "MerzScope",
        "NEC-MeshExplorer",
        "MindCrawler",
        "mnoGoSearch search engine software",
        "moget",
        "MOMspider",
        "Monster",
        "Motor",
        "Muncher",
        "Muninn",
        "Muscat Ferret",
        "Mwd.Search",
        "Internet Shinchakubin",
        "NDSpider",
        "Nederland.zoek",
        "NetCarta WebMap Engine",
        "NetMechanic",
        "NetScoop",
        "newscan-online",
        "NHSE Web Forager",
        "Nomad",
        "The NorthStar Robot",
        "nzexplorer",
        "ObjectsSearch",
        "Occam",
        "HKU WWW Octopus",
        "OntoSpider",
        "Openfind data gatherer",
        "Orb Search",
        "Pack Rat",
        "PageBoy",
        "ParaSite",
        "Patric",
        "pegasus",
        "The Peregrinator",
        "PerlCrawler 1.0",
        "Phantom",
        "PhpDig",
        "PiltdownMan",
        "Pimptrain.com's robot",
        "Pioneer",
        "html_analyzer",
        "Portal Juice Spider",
        "PGP Key Agent",
        "PlumtreeWebAccessor",
        "Poppi",
        "PortalB Spider",
        "GetterroboPlus Puu",
        "The Python Robot",
        "Raven Search",
        "RBSE Spider",
        "Resume Robot",
        "RoadHouse Crawling System",
        "RixBot",
        "Road Runner: The ImageScape Robot",
        "Robbie the Robot",
        "ComputingSite Robi/1.0",
        "RoboCrawl Spider",
        "RoboFox",
        "Robozilla",
        "Roverbot",
        "RuLeS",
        "SafetyNet Robot",
        "Scooter",
        "Sleek",
        "Search.Aus-AU.COM",
        "SearchProcess",
        "Senrigan",
        "SG-Scout",
        "ShagSeeker",
        "Shai'Hulud",
        "Sift",
        "Simmany Robot Ver1.0",
        "Site Valet",
        "Open Text Index Robot",
        "SiteTech-Rover",
        "Skymob.com",
        "SLCrawler",
        "Inktomi Slurp",
        "Smart Spider",
        "Snooper",
        "Solbot",
        "Spanner",
        "spider_monkey",
        "SpiderBot",
        "Spiderline Crawler",
        "SpiderMan",
        "SpiderView(tm)",
        "Spry Wizard Robot",
        "Site Searcher",
        "Suke",
        "suntek search engine",
        "Sven",
        "Sygol",
        "TACH Black Widow",
        "Tarantula",
        "tarspider",
        "Tcl W3 Robot",
        "TechBOT",
        "Templeton",
        "TeomaTechnologies",
        "TITAN",
        "TitIn",
        "The TkWWW Robot",
        "TLSpider",
        "UCSD Crawl",
        "UdmSearch",
        "UptimeBot",
        "URL Check",
        "URL Spider Pro",
        "Valkyrie",
        "Verticrawl",
        "Victoria",
        "vision-search",
        "void-bot",
        "VWbot",
        "The NWI Robot",
        "W3M2",
        "WallPaper (alias crawlpaper)",
        "the World Wide Web Wanderer",
        "w@pSpider by wap4.com",
        "WebBandit Web Spider",
        "WebCatcher",
        "WebCopy",
        "webfetcher",
        "The Webfoot Robot",
        "Webinator",
        "weblayers",
        "WebLinker",
        "WebMirror",
        "The Web Moose",
        "WebQuest",
        "Digimarc MarcSpider",
        "WebReaper",
        "webs",
        "Websnarf",
        "WebSpider",
        "WebVac",
        "webwalk",
        "WebWalker",
        "WebWatch",
        "Wget",
        "whatUseek Winona",
        "WhoWhere Robot",
        "Wired Digital",
        "Weblog Monitor",
        "w3mir",
        "WebStolperer",
        "The Web Wombat",
        "The World Wide Web Worm",
        "WWWC Ver 0.2.5",
        "WebZinger",
        "XGET",
        "AbiLogicBot",
        "Link Valet",
        "Link Validity Check",
        "LinkExaminer",
        "LinksManager.com_bot",
        "Mojoo Robot",
        "Notifixious",
        "online link validator",
        "Ploetz + Zeller",
        "Reciprocal Link System PRO",
        "REL Link Checker Lite",
        "SiteBar",
        "Vivante Link Checker",
        "W3C-checklink",
        "Xenu Link Sleuth",
        "CSE HTML Validator",
        "CSSCheck",
        "Cynthia",
        "HTMLParser",
        "P3P Validator",
        "W3C_CSS_Validator_JFouffa",
        "W3C_Validator",
        "WDG_Validator",
        "Altavista",
        "Altavista 1",
        "Altavista 2",
        "Altavista 3",
        "Altavista 4",
        "Ezooms",
        "MSN Search",
        "Googlebot",
        "Googlebot-Image",
        "Googlebot-News",
        "Googlebot-Image",
        "Googlebot-Video",
        "Googlebot-Mobile",
        "Media Partners GoogleBot",
        "Google Instant",
        "Mediapartners-Google/2.1",
        "Mediapartners-Google",
        "AdsBot-Google",
        "AdsBot-Google-Mobile-Apps",
        "Google Web Preview",
        "Google favicon",
        "+https://developers.google.com/+/web/snippet/",
        "YandexBot",
        "YandexImages",
        "YandexMetrika",
        "Yandex ?",
        "Yandex",
        "YaDirectFetcher",
        "YandexDirect",
        "vkShare",
        "OdklBot",
        "OdklBot/1.0",
        "facebookscraper",
        "facebookscraper/1.0",
        "facebookexternalhit",
        "facebookexternalhit/1.1",
        "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)",
        "facebook",
        "Facebot",
        "bitlybot",
        "Twitterbot/1.0",
        "Twitterbot",
        "GuzzleHttp",
        "archive.org_bot",
        "EmailWolf 1.00",
        "EmailWolf",
        "Adobe Application Manager 2.0",
        "Download Demon/3.5.0.11",
        "Download Demon",
        "Offline Explorer/2.5",
        "Offline Explorer",
        "SuperBot",
        "WebCopier",
        "Web Downloader",
        "WebZIP",
        "Microsoft URL Control",
        "SearchExpress",
        "Baidu",
        "Baiduspider",
        "Bing",
        "DuckDuckGo",
        "Ecosia",
        "Exalead",
        "Gigablast",
        "download",
        "spyder",
        "crawler",
        "Crawl",
        "crawl",
        "bot"
    ];

    /**
     * PlgSystemExBotHits constructor.
     *
     * @param object $subject
     * @param array  $config
     */
    public function __construct(& $subject, $config)
    {
        parent::__construct($subject, $config);
    }

    /**
     * @param $ua
     *
     * @return bool
     *
     * @since 1.0
     */
    public static function isBot($ua)
    {
        return self::strposa($ua, self::$agents);
    }

    /**
     * @param     $haystack
     * @param     $needle
     * @param int $offset
     *
     * @return bool
     *
     * @since 1.0
     */
    private static function strposa($haystack, $needle, $offset = 0)
    {
        if(!is_array($needle))
        {
            $needle = [$needle];
        }

        foreach ($needle as $query)
        {
            if(false !== strpos($haystack, $query, $offset))
            {
                return true;
            }
        }

        return false;
    }

    /**
     *
     * @return bool|void
     *
     * @since version
     */
    public function onAfterRender()
    {
        $app = JFactory::getApplication();

        if($app->getName() != 'site')
        {
            return;
        }

        $option = $app->input->get('option');
        $view   = $app->input->get('view');
        $id     = $app->input->get('id');

        if($option != 'com_content')
        {
            return;
        }

        $bot = $this->isBot($_SERVER['HTTP_USER_AGENT']);

        if(isset($view) && ($view == 'article') && ($bot == 1) && ($id > 0))
        {
            $db    = JFactory::getDbo();
            $query = $db->getQuery(true);
            $query->select('hits');
            $query->from('#__content');
            $query->where('`id` = ' . (int) $id);
            $db->setQuery($query);
            $currentHits = $db->loadResult();

            $updateHits = $currentHits - 1;
            $update     = 'UPDATE #__content SET HITS = ' . $updateHits . ' WHERE id = ' . (int) $id;
            $db->setQuery($update);
            $db->execute();
        }

        return;
    }
}